import '../globals.css'

export const metadata = {
  title: 'Admin Dashboard',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    
        <main>
        {children}
        </main>

  )
}